# Generated by Django 2.0.2 on 2019-11-27 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donasi', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='campaign',
            old_name='target_duit_donasi',
            new_name='goal',
        ),
        migrations.RemoveField(
            model_name='campaign',
            name='total_duit_donasi',
        ),
        migrations.RemoveField(
            model_name='campaign',
            name='total_orang_donasi',
        ),
        migrations.AddField(
            model_name='campaign',
            name='raised',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='campaign',
            name='total',
            field=models.IntegerField(default=0),
        ),
    ]
