# Generated by Django 2.0.2 on 2019-11-27 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donasi', '0002_auto_20191127_1422'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
